In [ ]:
#import libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.regularizers import l2
from keras.regularizers import l1
from keras.callbacks import EarlyStopping
from keras.layers import Dropout
from sklearn.metrics import recall_score,f1_score,precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
# load the dataset
dataset = pd.read_csv('diabetes.csv', delimiter=',')

In [ ]:
# split into input (X) and output (y) variables
X = dataset.drop("Outcome",axis = 1)
y = dataset["Outcome"]

In [ ]:
# test train split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
#convert target value
y_train_new = []
for i in y_train:
  if i == 1:
    y_train_new.append([1,0])
  else:
    y_train_new.append([0,1])
y_train_new = np.array(y_train_new) 

In [ ]:
y_test_new = []
for i in y_test:
  if i == 1:
    y_test_new.append([1,0])
  else:
    y_test_new.append([0,1])
y_test_new = np.array(y_test_new) 

## L2 REGULARIZATION

In [ ]:
# define the keras model with l2 regularization (alpha = 0.0001)
model_1 = Sequential()
model_1.add(Dense(500, input_dim=8, activation='sigmoid',kernel_regularizer=l2(0.0001),bias_regularizer=l2(0.0001),activity_regularizer=l2(0.0001)))
model_1.add(Dense(100, activation='sigmoid',kernel_regularizer=l2(0.0001),bias_regularizer=l2(0.0001),activity_regularizer=l2(0.0001)))
model_1.add(Dense(2, activation='softmax'))

In [ ]:
# compile the model
model_1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the model on the dataset
model_1.fit(X_train, y_train_new, epochs=1000, batch_size=70, verbose= 1) 

Epoch 1/1000
9/9 [==============================] - 1s 4ms/step - loss: 1.2638 - accuracy: 0.4284
Epoch 2/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7632 - accuracy: 0.6721
Epoch 3/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6637 - accuracy: 0.6929
Epoch 4/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6358 - accuracy: 0.6531
Epoch 5/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6167 - accuracy: 0.6792
Epoch 6/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6104 - accuracy: 0.6798
Epoch 7/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.5991 - accuracy: 0.7258
Epoch 8/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.5697 - accuracy: 0.7494
Epoch 9/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.5929 - accuracy: 0.6928
Epoch 10/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.5941 - accuracy: 0.7197
Epoch 11/1000
9/9 [

In [ ]:
# predict result
result = model_1.predict_classes(X_test)
y_test_conv=np.argmax(y_test_new, axis=1)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
# create confusion matrix
confusion_matrix(y_test_conv, result)

array([[37, 18],
       [24, 75]])

In [ ]:
# calculate accuracy, recall, precision, f score
accuracy = accuracy_score(y_test_conv, result)
print('Accuracy: %.3f' % accuracy)
recall = recall_score(y_test_conv, result)
print('Recall: %.3f' % recall)
precision = precision_score(y_test_conv, result)
print('Precision: %.3f' % precision)
score = f1_score(y_test_conv, result)
print('F-Measure: %.3f' % score)

Accuracy: 0.727
Recall: 0.758
Precision: 0.806
F-Measure: 0.781


## L1 REGULARIZATION

In [ ]:
# define the keras model with L1 regularization (alpha = 0.0001)
model_2 = Sequential()
model_2.add(Dense(500, input_dim=8, activation='sigmoid',kernel_regularizer=l1(0.0001),bias_regularizer=l1(0.0001),activity_regularizer=l1(0.0001)))
model_2.add(Dense(100, activation='sigmoid',kernel_regularizer=l1(0.0001),bias_regularizer=l1(0.0001),activity_regularizer=l1(0.0001)))
model_2.add(Dense(2, activation='softmax'))

In [ ]:
# compile the keras model
model_2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model_2.fit(X_train, y_train_new, epochs=1000, batch_size=70, verbose= 1)

Epoch 1/1000
9/9 [==============================] - 1s 3ms/step - loss: 0.9943 - accuracy: 0.5911
Epoch 2/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.8973 - accuracy: 0.6353
Epoch 3/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.8697 - accuracy: 0.6949
Epoch 4/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.8276 - accuracy: 0.7000
Epoch 5/1000
9/9 [==============================] - 0s 4ms/step - loss: 0.7789 - accuracy: 0.7348
Epoch 6/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.8050 - accuracy: 0.6964
Epoch 7/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7896 - accuracy: 0.6891
Epoch 8/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7686 - accuracy: 0.7301
Epoch 9/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7548 - accuracy: 0.7482
Epoch 10/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7412 - accuracy: 0.7538
Epoch 11/1000
9/9 [

In [ ]:
# predicting result
result = model_2.predict_classes(X_test)
y_test_conv=np.argmax(y_test_new, axis=1)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
# create confusion matrix
confusion_matrix(y_test_conv, result)

array([[34, 21],
       [18, 81]])

In [ ]:
# calculate accuracy, recall, precision, f score
accuracy = accuracy_score(y_test_conv, result)
print('Accuracy: %.3f' % accuracy)
recall = recall_score(y_test_conv, result)
print('Recall: %.3f' % recall)
precision = precision_score(y_test_conv, result)
print('Precision: %.3f' % precision)
score = f1_score(y_test_conv, result)
print('F-Measure: %.3f' % score)

Accuracy: 0.747
Recall: 0.818
Precision: 0.794
F-Measure: 0.806


## EARLY STOPPING REGULARIZATION

In [ ]:
#setting up early stopping function
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=50)

In [ ]:
#create model
model_3 = Sequential()
model_3.add(Dense(500, input_dim=8, activation='sigmoid'))
model_3.add(Dense(100, activation='sigmoid'))
model_3.add(Dense(2, activation='softmax'))

In [ ]:
# compile the keras model
model_3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model_3.fit(X_train, y_train_new,validation_split=0.3, epochs=1000, batch_size=70, verbose= 1,callbacks=[es])

Epoch 1/1000
7/7 [==============================] - 0s 31ms/step - loss: 0.6586 - accuracy: 0.6709 - val_loss: 0.6227 - val_accuracy: 0.6378
Epoch 2/1000
7/7 [==============================] - 0s 8ms/step - loss: 0.6031 - accuracy: 0.6595 - val_loss: 0.6339 - val_accuracy: 0.6270
Epoch 3/1000
7/7 [==============================] - 0s 7ms/step - loss: 0.5985 - accuracy: 0.6642 - val_loss: 0.5974 - val_accuracy: 0.7243
Epoch 4/1000
7/7 [==============================] - 0s 7ms/step - loss: 0.5880 - accuracy: 0.6865 - val_loss: 0.6374 - val_accuracy: 0.6162
Epoch 5/1000
7/7 [==============================] - 0s 7ms/step - loss: 0.6083 - accuracy: 0.7010 - val_loss: 0.5918 - val_accuracy: 0.7027
Epoch 6/1000
7/7 [==============================] - 0s 7ms/step - loss: 0.5724 - accuracy: 0.6945 - val_loss: 0.5856 - val_accuracy: 0.7243
Epoch 7/1000
7/7 [==============================] - 0s 7ms/step - loss: 0.5648 - accuracy: 0.6980 - val_loss: 0.5858 - val_accuracy: 0.6757
Epoch 8/1000
7/7 [=

In [ ]:
# predicting result
result = model_3.predict_classes(X_test)
y_test_conv=np.argmax(y_test_new, axis=1)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
# create confusion matrix
confusion_matrix(y_test_conv, result)

array([[30, 25],
       [11, 88]])

In [ ]:
# calculate accuracy, recall, precision, f score
accuracy = accuracy_score(y_test_conv, result)
print('Accuracy: %.3f' % accuracy)
recall = recall_score(y_test_conv, result)
print('Recall: %.3f' % recall)
precision = precision_score(y_test_conv, result)
print('Precision: %.3f' % precision)
score = f1_score(y_test_conv, result)
print('F-Measure: %.3f' % score)

Accuracy: 0.766
Recall: 0.889
Precision: 0.779
F-Measure: 0.830


## DROPOUT REGULARIZATION

In [ ]:
#create keras model with dropout layer
model_4 = Sequential()
model_4.add(Dense(500, input_dim=8, activation='sigmoid'))
model_4.add(Dropout(0.3))
model_4.add(Dense(100, activation='sigmoid'))
model_4.add(Dropout(0.3))
model_4.add(Dense(2, activation='softmax'))

In [ ]:
# compile the keras model
model_4.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model_4.fit(X_train, y_train_new, epochs=1000, batch_size=70, verbose= 1) #validation_data=(X_test, y_test_new))

Epoch 1/1000
9/9 [==============================] - 0s 3ms/step - loss: 1.0978 - accuracy: 0.4327
Epoch 2/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7655 - accuracy: 0.6546
Epoch 3/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.7064 - accuracy: 0.5548
Epoch 4/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6334 - accuracy: 0.6726
Epoch 5/1000
9/9 [==============================] - 0s 2ms/step - loss: 0.6102 - accuracy: 0.6675
Epoch 6/1000
9/9 [==============================] - 0s 2ms/step - loss: 0.6030 - accuracy: 0.6741
Epoch 7/1000
9/9 [==============================] - 0s 3ms/step - loss: 0.6135 - accuracy: 0.6805
Epoch 8/1000
9/9 [==============================] - 0s 2ms/step - loss: 0.5945 - accuracy: 0.6614
Epoch 9/1000
9/9 [==============================] - 0s 2ms/step - loss: 0.5896 - accuracy: 0.6942
Epoch 10/1000
9/9 [==============================] - 0s 2ms/step - loss: 0.5921 - accuracy: 0.7036
Epoch 11/1000
9/9 [

In [ ]:
# predicting result
result = model_4.predict_classes(X_test)
y_test_conv=np.argmax(y_test_new, axis=1)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
# create confusion matrix
confusion_matrix(y_test_conv, result)

array([[35, 20],
       [17, 82]])

In [ ]:
# calculate accuracy, recall, precision, f score
accuracy = accuracy_score(y_test_conv, result)
print('Accuracy: %.3f' % accuracy)
recall = recall_score(y_test_conv, result)
print('Recall: %.3f' % recall)
precision = precision_score(y_test_conv, result)
print('Precision: %.3f' % precision)
score = f1_score(y_test_conv, result)
print('F-Measure: %.3f' % score)

Accuracy: 0.760
Recall: 0.828
Precision: 0.804
F-Measure: 0.816
